server:
  servlet:
    context-path: /wudada
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 8192
  max-http-header-size: 8192


spring:
  profiles:
    active:
    #- test    #测试环境
    - dev     #开发环境
    #- prod    #生产环境
    - redis   #redis配置

  datasource:
    url: jdbc:mysql://localhost:3306/wudada?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5    #初始大小
      minIdle: 5        #最小值
      maxActive: 100    #最大值
      maxWait: 60000    #获取连接等待超时时间
      max-pool-prepared-statement-per-connection-size: 20
      timeBetweenEvictionRunsMillis: 60000    #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000     #一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true   #设置为true,防止取到的连接不可用
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j  #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
                                #监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
      filter:
        stat:
          log-slow-sql: true
          db-type: mysql
          slow-sql-millis: 5000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        deny: #访问黑名单

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    #suffix: .html  #thymeleaf默认.html 可不写
  #resources:         #静态资源路径
    #static-locations:
    #- classpath:/static/
    #- classpath:/templates/

  #发送邮件配置  
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com       #服务器地址
    port: 465        #端口
    protocol: smtp    #协议
    username: 2315504505@qq.com    #账号2315504505@qq.com
    password: eajmwmjbswsueadd    #密码
    properties:                #SSL认证
      mail: 
        smtp:
          auth: true
          socketFactory: 
            class: javax.net.ssl.SSLSocketFactory
          ssl: 
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB        #最大文件上传大小
      max-request-size: 100MB    #最大请求大小

  #配置热部署是否开启
  devtools:
    restart:
      enabled: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#配置mybatis xml地址
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #别名
  type-aliases-package: com.java.entity
  configuration:
    #打印sql和查询结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #xml热加载
    refresh: true


#logging:
#  level:
#    com:
#      java:
#        mapper: debug      #输出sql


######################################################      
#自定义属性
mail:
  username: 2315504505@qq.com


