spring:
  redis:
    host: localhost   #IP地址
    port: 6379        #端口
    password:         #密码
    timeout: 0        #超时时间
    pool:
      max-active: 8   #最大连接数
      max-wait: -1    #最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0     #最小空闲连接
      max-idle: 8     #最大空闲连接